### ISSUE TITLE
How Can I Get the Posted Data?

### ISSUE THREAD

**Issue by richdev135** [TypeformIO/form-submit-demo#1]
This is a great example of how to trap the submit event, but it doesn't show how to read the submitted data. Is there a chance you could include that in this demo?  I've got this code working and I'm looking thru the ev object, but I'm not finding the form data.

Thanks!!

**Comment by ghost** [comment]
Hi @richdev135! The form_submit event does not include the submit data; it is merely intended to notify you so that you can trigger UI changes. On Typeform I/O, you can set up a `webhook_submit_url` on form creation. This is where you will receive the submit data.

**Comment by richdev135** [comment]
OK, thanks!  I'm creating a form using the typeform wizard (workspace?) :-)  I don't see where I include this webhook_submit_url value in my form. Any advice?  

(You can see my ultimately beautiful form at: https://richdev135.typeform.com/to/yEjGyO) 

thanks!

**Comment by ghost** [comment]
Oh, right. This repository contains a sample embedding for Typeform I/O forms, and my above comment referred to those as well. Unfortunately, Typeform.com does not support webhooks just yet. On Typeform.com, results will be shown to you on the Analyse panel, or you can fetch them through the Data API.

For Typeform.com support, please use [the helpcenter](http://helpcenter.typeform.com).
